config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks:  "users/omniauth_callbacks"
  }

  devise_scope :user do
    get 'users/select' => 'users/registrations#select'
    get 'users/confirm_phone' => 'users/registrations#confirm_phone'    ## ③電話番号認証画面のアクション
    get 'users/new_address' => 'users/registrations#new_address'        ## ④addressのフォームのアクション
    post 'users/create_address' => 'users/registrations#create_address' ## ⑤addressをsaveするアクション
  end

  resources :users, only: [:show]

  resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy]  do
    member do
      get "purchase_confirmation"
      post "purchase"
    end
    collection do
      get 'search'
    end
  end
  resources :categories, only: [:index, :show]
  namespace :api do
    resources :categories, only: :index, defaults: { format: 'json' }
  end
  resources :cards, only: [:new, :index, :create, :destroy] 

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  def self.get_card(customer_token)  ## カード情報を取得する。支払い方法ページで使用する。
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]

    customer = Payjp::Customer.retrieve(customer_token)
    card_data = customer.cards.first
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :redirect_registered_user, except: [:index, :destroy]

  def index
    @card = Card.get_card(current_user.card.customer_token) if current_user.card
  end

  def new
    @card = Card.new
    now_year = Time.current.year
    @exp_years = []
    6.times do |i|
      year = now_year + i
      @exp_years << [year % 100, year]
    end
  end

  def create
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
    customer = Payjp::Customer.create(card: params[:payjp_token]) ## 顧客の作成
    card = current_user.build_card(card_token: params[:card_token], customer_token: customer.id)
    if card.save
      redirect_to cards_path, notice: "カードの登録が完了しました。"
    else
      redirect_to new_card_path, alert: "カードの登録に失敗しました。"
    end
  end

  def destroy
    card = current_user.card
    if card.destroy
      redirect_to cards_path, notice: "カードの削除が完了しました。"
    else
      redirect_to cards_path, notice: "カードの削除に失敗しました。"
    end
  end

  private
  def redirect_registered_user
    redirect_to cards_path, alert: "既にカードを登録済みです。" if current_user.card
  end
end

app/views/cards/index.html.haml
.mypage.horizontal-padding-15
  = render 'shared/side_bar'
  .mypage-main
    .block
      .block__menu
        支払い方法
    .block
      .block__menu
        クレジットカード一覧
      -# ログイン中のユーザーがカード登録済みなら
      -if @card
        .block__main
          .card-show.horizontal-padding-25
            .card-show__data
              = image_tag 'icon_visa.png'
              = "************" + @card[:last4]
              %br
              = @card[:exp_month]
              \/
              = @card[:exp_year]
              %br
              = @card[:brand]
            = link_to "削除する", card_path(current_user.card), method: :delete, class: "delete-button"
      - else
        .block__main.horizontal-padding-25
          = link_to new_card_path, data: {turbolinks: false} do
            .button.regist-card
              = icon "far", "credit-card"
              %span.button__text
                新規登録
    .block
      .block__main
        = link_to "支払い方法について >", "#"

app/views/cards/new.html.haml
.mypage.horizontal-padding-15
  = render 'shared/side_bar'
  .mypage-main
    .block.horizontal-padding-25
      .block__menu
        支払い方法
    .block.horizontal-padding-25
      = form_with model: @card, id: "card_form" do |f|
        .input-field
          .input-field-main
            = f.label :hoge, "カード番号"
            %span.required-true
              必須
            %br
            = f.text_field :hoge, required: true, maxlength: 16, id: "card_number_form", placeholder: "1234 5678 1234 5678"
            #card-icons
              = image_tag 'icon_visa.png'
              = image_tag 'icon_master.jpg'
              = image_tag 'icon_saison.png'
              = image_tag 'icon_jcb.png'
              = image_tag 'icon_american.svg'
              = image_tag 'icon_diners.png'
              = image_tag 'icon_discover.png'
        .input-field
          .input-field-main
            = f.label :hoge, "有効期限"
            %span.required-true
              必須
            .input-field-multiple
              = f.select :hoge, 1..12, {include_blank: "---"}, id: "exp_month_form"
              .input-field-multiple__separate-text
                月
              = f.select :hoge, 20..25, {include_blank: "---"}, id: "exp_year_form"
              .input-field-multiple__separate-text
                年
        .input-field
          .input-field-main
            = f.label :hoge, "セキュリティコード"
            %span.required-true
              必須
            %br
            = f.text_field :hoge, required: true,  id: "cvc_form", placeholder: "カード背面４桁もしくは３桁の番号"
            %br
            .information
              .information__right.font-skyblue
                = icon "fas", "question-circle", class:"header-bottom-left__button--red"
                カード裏面の番号とは？
            #card_token
        = f.submit "次へ進む", class:"button back-red font-white", id: "regist_card"